### ISSUE TITLE
Pass packages parameter in interactive docker (jupyter)

### ISSUE THREAD

**Issue by KimKiHyuk** [indy-3rdman/docker-dotnet-spark#14]
@indy-3rdman 
I've encountered some problem using interactive docker (jupyter)

To run my spark program, I have to pass a parameter like
```spark-submit --packages org.apache.spark:spark-avro_2.11:2.4.6 ...```

but i don't get it how to do it in jupyter.

what should i do to solve it?

```
[2020-11-26T00:28:42.3520910Z] [c2435164f8aa] [Error] [JvmBridge] org.apache.spark.sql.AnalysisException: Failed to find data source: avro. Avro is built-in but external data source module since Spark 2.4. Please deploy the application as per the deployment section of "Apache Avro Data Source Guide".;
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:666)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:733)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:248)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:232)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:159)
	at org.apache.spark.api.dotnet.DotnetBackendHandler.$anonfun$handleBackendRequest$2(DotnetBackendHandler.scala:99)
	at org.apache.spark.api.dotnet.ThreadPool$$anon$1.run(ThreadPool.scala:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by indy-3rdman** [comment]
@KimKiHyuk , I think the most flexible approach would be to just mimic what start-spark-debug.sh does.

1) Copy the correct microsoft-spark jar in the directory in which you want to create your notebook.
e.g. `cp "${HOME}/microsoft-spark-2-4_2.11-1.0.0.jar" "$(pwd)"`

2) Start .NET for Apache Spark in debug mode.
e.g. `/spark/bin/spark-submit --packages org.apache.spark:spark-avro_2.11:2.4.6 --class org.apache.spark.deploy.dotnet.DotnetRunner --jars "$(pwd)/*.jar" --master local microsoft-spark-2-4_2.11-1.0.0.jar debug 5567`

![interactive-add-package](https://user-images.githubusercontent.com/60756651/100520499-48bef500-319e-11eb-926e-9b7c259c6c11.gif)

After that you should be able create a new C# notebook, install the Microsoft.Spark NuGet package, create your SparkSession and use your package.

Could you please let me know, whether that works for you as well?

**Comment by KimKiHyuk** [comment]
thank you so much! it works well
